### ISSUE TITLE
PR Pipeline has broken - Not fetching the Ibmcloud API Key

### ISSUE THREAD

**Issue by JineshPaul** [IBM-Cloud/terraform-ibmcloud-modules#17]
# What's the issue?

The isssue is that:
PR Pipeline has broken - Not fetching the Ibmcloud API Key
# Definition of Done

It's required to be done:

**Comment by chuesgen** [comment]
Will start working on this now!

**Comment by chuesgen** [comment]
Environment variables set on the build are not supported by travis, or they do not carry over to the fork.  We will need to use branches for now for PR's
